<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Week 8 Linear Regression | GESC-258 Schedule</title>
  <meta name="description" content="Schedule, readings, and labs for GESC 258, Winter 2021." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Week 8 Linear Regression | GESC-258 Schedule" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Schedule, readings, and labs for GESC 258, Winter 2021." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Week 8 Linear Regression | GESC-258 Schedule" />
  
  <meta name="twitter:description" content="Schedule, readings, and labs for GESC 258, Winter 2021." />
  

<meta name="author" content="Colin Robertson" />


<meta name="date" content="2021-03-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="anova.html"/>

<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">GESC 258</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="introduction-and-research-design.html"><a href="introduction-and-research-design.html"><i class="fa fa-check"></i><b>1</b> Introduction and Research Design</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-and-research-design.html"><a href="introduction-and-research-design.html#what-we-cover-this-week"><i class="fa fa-check"></i><b>1.1</b> What We Cover this Week</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-and-research-design.html"><a href="introduction-and-research-design.html#readings"><i class="fa fa-check"></i><b>1.2</b> Readings</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-and-research-design.html"><a href="introduction-and-research-design.html#lab"><i class="fa fa-check"></i><b>1.3</b> Lab</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="w2title.html"><a href="w2title.html"><i class="fa fa-check"></i><b>2</b> Probability Distributions - Normal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="w2title.html"><a href="w2title.html#w2cover"><i class="fa fa-check"></i><b>2.1</b> What we cover this week</a></li>
<li class="chapter" data-level="2.2" data-path="w2title.html"><a href="w2title.html#w2read"><i class="fa fa-check"></i><b>2.2</b> Readings</a></li>
<li class="chapter" data-level="2.3" data-path="w2title.html"><a href="w2title.html#w2lab"><i class="fa fa-check"></i><b>2.3</b> Lab</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="w2title.html"><a href="w2title.html#w2data"><i class="fa fa-check"></i><b>2.3.1</b> Tree Circumference Data</a></li>
<li class="chapter" data-level="2.3.2" data-path="w2title.html"><a href="w2title.html#recalling-measures-of-central-tendency-and-dispersion"><i class="fa fa-check"></i><b>2.3.2</b> Recalling measures of central tendency and dispersion</a></li>
<li class="chapter" data-level="2.3.3" data-path="w2title.html"><a href="w2title.html#the-normal-distribution"><i class="fa fa-check"></i><b>2.3.3</b> The Normal Distribution</a></li>
<li class="chapter" data-level="2.3.4" data-path="w2title.html"><a href="w2title.html#using-z-scores-instead-of-raw-data-to-more-easily-find-probabilities-from-a-normal-distribution"><i class="fa fa-check"></i><b>2.3.4</b> Using z-scores instead of raw data to more easily find probabilities from a normal distribution</a></li>
<li class="chapter" data-level="2.3.5" data-path="w2title.html"><a href="w2title.html#assignment"><i class="fa fa-check"></i><b>2.3.5</b> Assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="w3title.html"><a href="w3title.html"><i class="fa fa-check"></i><b>3</b> Probability Distributions II - Others</a>
<ul>
<li class="chapter" data-level="3.1" data-path="w3title.html"><a href="w3title.html#w3cover"><i class="fa fa-check"></i><b>3.1</b> What we cover this week</a></li>
<li class="chapter" data-level="3.2" data-path="w3title.html"><a href="w3title.html#w3read"><i class="fa fa-check"></i><b>3.2</b> Readings</a></li>
<li class="chapter" data-level="3.3" data-path="w3title.html"><a href="w3title.html#w3lab"><i class="fa fa-check"></i><b>3.3</b> Lab</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="w3title.html"><a href="w3title.html#how-does-honeycomb-patterns-in-sandstone-form"><i class="fa fa-check"></i><b>3.3.1</b> How does honeycomb patterns in sandstone form?</a></li>
<li class="chapter" data-level="3.3.2" data-path="w3title.html"><a href="w3title.html#study-image"><i class="fa fa-check"></i><b>3.3.2</b> Study Image</a></li>
<li class="chapter" data-level="3.3.3" data-path="w3title.html"><a href="w3title.html#analyzing-count-data"><i class="fa fa-check"></i><b>3.3.3</b> Analyzing Count Data</a></li>
<li class="chapter" data-level="3.3.4" data-path="w3title.html"><a href="w3title.html#w3assign"><i class="fa fa-check"></i><b>3.3.4</b> Assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="w4title.html"><a href="w4title.html"><i class="fa fa-check"></i><b>4</b> Sampling Distributions and Confidence Intervals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="w4title.html"><a href="w4title.html#w4cover"><i class="fa fa-check"></i><b>4.1</b> What we cover this week</a></li>
<li class="chapter" data-level="4.2" data-path="w4title.html"><a href="w4title.html#w4read"><i class="fa fa-check"></i><b>4.2</b> Readings</a></li>
<li class="chapter" data-level="4.3" data-path="w4title.html"><a href="w4title.html#w4lab"><i class="fa fa-check"></i><b>4.3</b> Lab</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="w4title.html"><a href="w4title.html#sampling-distribution-of-the-mean"><i class="fa fa-check"></i><b>4.3.1</b> Sampling Distribution of the Mean</a></li>
<li class="chapter" data-level="4.3.2" data-path="w4title.html"><a href="w4title.html#confidence-intervals"><i class="fa fa-check"></i><b>4.3.2</b> Confidence Intervals</a></li>
<li class="chapter" data-level="4.3.3" data-path="w4title.html"><a href="w4title.html#w4assign"><i class="fa fa-check"></i><b>4.3.3</b> Assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hypothesis-testing-concepts.html"><a href="hypothesis-testing-concepts.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Testing Concepts</a>
<ul>
<li class="chapter" data-level="5.1" data-path="hypothesis-testing-concepts.html"><a href="hypothesis-testing-concepts.html#w6cover"><i class="fa fa-check"></i><b>5.1</b> What we cover this week</a></li>
<li class="chapter" data-level="5.2" data-path="hypothesis-testing-concepts.html"><a href="hypothesis-testing-concepts.html#w6read"><i class="fa fa-check"></i><b>5.2</b> Readings</a></li>
<li class="chapter" data-level="5.3" data-path="hypothesis-testing-concepts.html"><a href="hypothesis-testing-concepts.html#w6lab"><i class="fa fa-check"></i><b>5.3</b> Lab</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="hypothesis-testing-concepts.html"><a href="hypothesis-testing-concepts.html#w6assign"><i class="fa fa-check"></i><b>5.3.1</b> Assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html"><i class="fa fa-check"></i><b>6</b> Hypothesis Testing I</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#w7cover"><i class="fa fa-check"></i><b>6.1</b> What we cover this week</a></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#w7read"><i class="fa fa-check"></i><b>6.2</b> Readings</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#w7lab"><i class="fa fa-check"></i><b>6.3</b> Lab</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#examining-with-fake-data"><i class="fa fa-check"></i><b>6.3.1</b> Examining with Fake Data</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#one-sample-hypothesis-testing"><i class="fa fa-check"></i><b>6.3.2</b> One-Sample Hypothesis Testing</a></li>
<li class="chapter" data-level="6.3.3" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#two-sample-hypothesis-testing"><i class="fa fa-check"></i><b>6.3.3</b> Two-Sample Hypothesis Testing</a></li>
<li class="chapter" data-level="6.3.4" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#gps-dataset"><i class="fa fa-check"></i><b>6.3.4</b> GPS Dataset</a></li>
<li class="chapter" data-level="6.3.5" data-path="hypothesis-testing-i.html"><a href="hypothesis-testing-i.html#lab-assignment"><i class="fa fa-check"></i><b>6.3.5</b> Lab Assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>7</b> ANOVA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="anova.html"><a href="anova.html#w8cover"><i class="fa fa-check"></i><b>7.1</b> What we cover this week</a></li>
<li class="chapter" data-level="7.2" data-path="anova.html"><a href="anova.html#w8read"><i class="fa fa-check"></i><b>7.2</b> Readings</a></li>
<li class="chapter" data-level="7.3" data-path="anova.html"><a href="anova.html#w8lab"><i class="fa fa-check"></i><b>7.3</b> Lab</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="anova.html"><a href="anova.html#analysis-of-variance-in-r"><i class="fa fa-check"></i><b>7.3.1</b> Analysis of Variance in R</a></li>
<li class="chapter" data-level="7.3.2" data-path="anova.html"><a href="anova.html#w8labass"><i class="fa fa-check"></i><b>7.3.2</b> Lab Assignment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>8</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="linear-regression.html"><a href="linear-regression.html#w9cover"><i class="fa fa-check"></i><b>8.1</b> What we cover this week</a></li>
<li class="chapter" data-level="8.2" data-path="linear-regression.html"><a href="linear-regression.html#w9read"><i class="fa fa-check"></i><b>8.2</b> Readings</a></li>
<li class="chapter" data-level="8.3" data-path="linear-regression.html"><a href="linear-regression.html#w9lab"><i class="fa fa-check"></i><b>8.3</b> Lab</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="linear-regression.html"><a href="linear-regression.html#w9labass"><i class="fa fa-check"></i><b>8.3.1</b> Lab Assignment</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li> &nbsp Instructor: Dr. Colin Robertson</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GESC-258 Schedule</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression" class="section level1" number="8">
<h1><span class="header-section-number">Week 8</span> Linear Regression</h1>
<p>This week we introduce linear regression and the various statistical inference tools used in linear regression analysis.</p>
<div id="w9cover" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> What we cover this week</h2>
<ul>
<li>Linear regression concepts</li>
<li>Ordinary least squares</li>
<li>Hypothesis testing and regression</li>
</ul>
</div>
<div id="w9read" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Readings</h2>
<p><a href="https://onlinestatbook.com/2/regression/regression.html" target="_blank">Chapter XV in online textbook</a></p>
<p>Key sections:</p>
<ul>
<li>Introduction to simple linear regression</li>
<li>Partitioning sums of squares</li>
<li>Standard error of the estimate</li>
<li>Inferential statistics for b and r</li>
</ul>
</div>
<div id="w9lab" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> Lab</h2>
<p>This lab is due on the Dropbox on MyLearningSpace on <strong>Friday April 9th</strong></p>
<p>For this lab we will use one of the built in datasets. R has a number of sample datasets and many packages also have sample data that comes with them. We will use the <code>mtcars</code> dataset that includes data from a 1974 Motor Trend magazine describing characteristics of 32 cars. You can check out the details of the variables by examining the documentation with <code>?mtcars</code></p>
<p>The <code>mtcars</code> dataset is a data frame. This is a tabular data structure, the individual columns of the data frame can be accessed using the $ notation.</p>
<p>For example:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="linear-regression.html#cb143-1" aria-hidden="true"></a><span class="kw">summary</span>(mtcars<span class="op">$</span>mpg)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   10.40   15.43   19.20   20.09   22.80   33.90</code></pre>
<p>We will use this dataset to explore linear regression. The function for fitting a linear regression model is <code>lm</code>. We can create a linear regression object by assigning the output of <code>lm</code> to a new variable, or we wrap it in a <code>summary</code> command. Here is an example</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="linear-regression.html#cb145-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(mtcars<span class="op">$</span>mpg<span class="op">~</span>mtcars<span class="op">$</span>wt))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mtcars$mpg ~ mtcars$wt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## mtcars$wt    -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528,	Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
<p>Another way to do the same thing is to just specify the column names but then set the data argument in the <code>lm</code> function to specify the name of the data frame that the columns are in</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="linear-regression.html#cb147-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(mpg<span class="op">~</span>wt, <span class="dt">data=</span>mtcars))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## wt           -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528,	Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
<p>Examining the description of the columns with <code>?mtcars</code> we can see that this is creating a linear regression model with Miles/(US) gallon as the dependent variable and Weight (1000 lbs) as the independent variable. Thinking about this, and the fact these are cars from the early 1970s, we might expect the relationship between these two variables to be <strong>negative</strong> - as car weight increases the miles/per gallon should decrease. Looking at the output above, we see our two coefficient estimates are in the “Estimate” column. The “(Intercept)” Estimate is 37.2851 and the slope coefficient for <code>wt</code> is -5.3445.</p>
<p>We interpret the Y-intercept as the value of <code>Y</code> when the <code>X</code> variable is zero. Often, the Y-intercept does not have any real meaning. The slope coefficient is usually what we are interested in. Here a value of -5.3445 means the average change in Miles/(US) gallon for a one-unit increase in weight. It is important to think about what the units the data are measured in. We can see from the documentation that the <code>wt</code> variable is measured in 1000s of lbs. Therefore for every extra 1000lbs of car weight, the miles per gallon decreases by -5.3445.</p>
<p>The next column in the regression output is the standard error column. These are standard errors on the coeffient estimates, and next to that is the t-statistics. Recall that these are t-test on if the coefficents are significant, i.e., are they statistically different from zero.</p>
<p><span class="math inline">\(t = \frac{\beta_1 - 0}{\beta_{1se}}\)</span></p>
<p>so for the <code>wt</code> variable, the t-statistic is just <span class="math inline">\(t=\frac{-5.3445 - 0}{0.5591}=-9.559\)</span> and the last column is the p-value on the hypothesis test.</p>
<p>The Residual standard error is the standard error of the estimate. We get the R-squared as well which we can calculate from the SSR/SST formulas. Or we can see the sums of squares by using the <code>anova</code> function such as</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="linear-regression.html#cb149-1" aria-hidden="true"></a><span class="kw">anova</span>(<span class="kw">lm</span>(mpg<span class="op">~</span>wt, <span class="dt">data=</span>mtcars))</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: mpg
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## wt         1 847.73  847.73  91.375 1.294e-10 ***
## Residuals 30 278.32    9.28                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>where SSR=847.73, SSE=278.32, and SST = SSR+SSE, so <span class="math inline">\(R^2=\frac{SSR}{SST}\)</span> - which expresses the percentage of variation in the Y variable explained by the X variable. Here we see that <span class="math inline">\(R^2=\frac{847.73}{1126.05}=0.7528\)</span>. We also see the F statistic which is a hypothesis test on the model as a whole, and just as in our <code>anova</code> for comparing means, we are using the SSR/SST as the basis for the F statistic.</p>
<p>We often want to get the model residuals to examine their distribution. We can do this by using the <code>residuals</code> function</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="linear-regression.html#cb151-1" aria-hidden="true"></a>err &lt;-<span class="st"> </span><span class="kw">residuals</span>(<span class="kw">lm</span>(mpg<span class="op">~</span>wt, <span class="dt">data=</span>mtcars))</span>
<span id="cb151-2"><a href="linear-regression.html#cb151-2" aria-hidden="true"></a><span class="kw">hist</span>(err)</span></code></pre></div>
<p><img src="GESC258-2020_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>which we can see are centered on zero and approximately normally distributed. We can also check the heterogeneity by comparing the residuals against the x values</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="linear-regression.html#cb152-1" aria-hidden="true"></a><span class="kw">plot</span>(mtcars<span class="op">$</span>wt, err)</span></code></pre></div>
<p><img src="GESC258-2020_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>we can also see some of these diagnostic plots by creating an <code>lm</code> object by assigning the output of <code>lm</code> to a new object and then plotting it. <a href="https://data.library.virginia.edu/diagnostic-plots/">Read up on how to interpret these diagnostics here</a></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="linear-regression.html#cb153-1" aria-hidden="true"></a>lmo &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span>wt, <span class="dt">data=</span>mtcars)</span>
<span id="cb153-2"><a href="linear-regression.html#cb153-2" aria-hidden="true"></a><span class="kw">plot</span>(lmo)</span></code></pre></div>
<p><img src="GESC258-2020_files/figure-html/unnamed-chunk-84-1.png" width="672" /><img src="GESC258-2020_files/figure-html/unnamed-chunk-84-2.png" width="672" /><img src="GESC258-2020_files/figure-html/unnamed-chunk-84-3.png" width="672" /><img src="GESC258-2020_files/figure-html/unnamed-chunk-84-4.png" width="672" /></p>
<div id="w9labass" class="section level3" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> Lab Assignment</h3>
<ol style="list-style-type: decimal">
<li><p>Create a regression model using Miles/(US) gallon as the dependent variable and Gross horsepower as the independent variable. Report all model statistics and comment on the model diagnostics. Include a basic scatterplot of the data as well. Write a sentence or two interpreting this analysis. (out of 5)</p></li>
<li><p>Create a regression model using two other variables from the <code>mtcars</code> dataset (i.e., not miles per gallon as dependent and horsepower as independent). Ensure that the there is a plausible causal connection between the independent and dependent variables. Report all model statistics and comment on the model diagnostics. Include a basic scatterplot of the data as well. Write a sentence or two interpreting this analysis. (out of 5)</p></li>
<li><p>What would be the problem with using all of the variables (other than <code>mpg</code>) in the <code>mtcars</code> dataset as independent variables to predict <code>mpg</code>? (out of 5)</p></li>
<li><p>Look at the other datasets available in the base package by checking <code>library(help = "datasets")</code>. Pick one and create a linear regression model. Report all model statistics and comment on the model diagnostics. Include a basic scatterplot of the data as well. Write a sentence or two interpreting this analysis. (out of 5)</p></li>
<li><p>Using the <code>quakes</code> dataset, examine whether there is a significant relationship between earth quake depth and earthquake magnitude. Report all relevant statistics and interpret the findings. (out of 5)</p></li>
<li><p>Using everything you now know how to do, explore a research question of interest in detail, using either your own external dataset or one of the ones used previously in lab or the built in datasets. In your analysis, do a confidence interval, at least three graphs, one hypothesis test, and one regression analysis. Try to put your analysis together into a logical flow and write a paragraph or two interpreting your findings. (out of 15)</p></li>
</ol>

<!-- # Linear Regression Concepts -->
<!-- We have finished a nice book. -->

<!-- # Regression Inference -->
<!-- We have finished a nice book. -->

<!-- # Critical Research Reading -->
<!-- We have finished a nice book. 



</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="anova.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["GESC258-2020.pdf", "GESC258-2020.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
